'use client'

import { useState, useEffect } from 'react'
import { Calendar, Clock, User, Mail, Phone, Trash2, Search, X, Plus, RefreshCw, Settings } from 'lucide-react'
import {
  loadAppointments,
  cancelAppointment,
  getAppointmentsByDate,
  getNextAvailableDates,
  isAvailableDay,
  getDayName,
  MAX_BOOKINGS_PER_SLOT,
  loadAvailableDates,
  addAvailableDate,
  removeAvailableDate,
  loadAvailableTimeSlots,
  addAvailableTimeSlot,
  removeAvailableTimeSlot,
  getAvailableTimeSlotsList,
  type Appointment
} from '@/lib/appointments-manager'

export default function AppointmentsAdminPage() {
  const [appointments, setAppointments] = useState<Appointment[]>([])
  const [searchTerm, setSearchTerm] = useState<string>('')
  const [selectedDate, setSelectedDate] = useState<string>('')
  
  // Gestion des créneaux disponibles
  const [manualDate, setManualDate] = useState<string>('')
  const [manualTimeSlot, setManualTimeSlot] = useState<string>('')
  const [customDates, setCustomDates] = useState<string[]>([])
  const [customTimeSlots, setCustomTimeSlots] = useState<string[]>([])
  
  // Génération automatique
  const [autoGenerateCount, setAutoGenerateCount] = useState<number>(20)
  const [autoGeneratedDates, setAutoGeneratedDates] = useState<string[]>([])

  // Fonction pour recharger toutes les données
  const reloadAllData = () => {
    const allAppointments = loadAppointments()
    allAppointments.sort((a, b) => {
      if (a.date !== b.date) return a.date.localeCompare(b.date)
      return a.timeSlot.localeCompare(b.timeSlot)
    })
    setAppointments(allAppointments)
    
    const dates = loadAvailableDates()
    setCustomDates([...dates])
    
    const slots = loadAvailableTimeSlots()
    setCustomTimeSlots([...slots])
    
    const generatedDates = getNextAvailableDates(autoGenerateCount)
    setAutoGeneratedDates([...generatedDates])
  }

  // Charger les données
  useEffect(() => {
    reloadAllData()
    
    const appointmentsHandler = () => {
      const allAppointments = loadAppointments()
      allAppointments.sort((a, b) => {
        if (a.date !== b.date) return a.date.localeCompare(b.date)
        return a.timeSlot.localeCompare(b.timeSlot)
      })
      setAppointments(allAppointments)
    }
    
    const datesHandler = () => {
      const dates = loadAvailableDates()
      setCustomDates([...dates])
      const generatedDates = getNextAvailableDates(autoGenerateCount)
      setAutoGeneratedDates([...generatedDates])
    }
    
    const timeSlotsHandler = () => {
      const slots = loadAvailableTimeSlots()
      setCustomTimeSlots([...slots])
    }
    
    window.addEventListener('appointments-updated', appointmentsHandler)
    window.addEventListener('available-dates-updated', datesHandler)
    window.addEventListener('available-time-slots-updated', timeSlotsHandler)
    
    return () => {
      window.removeEventListener('appointments-updated', appointmentsHandler)
      window.removeEventListener('available-dates-updated', datesHandler)
      window.removeEventListener('available-time-slots-updated', timeSlotsHandler)
    }
  }, [autoGenerateCount])

  // Filtrer les rendez-vous
  const filteredAppointments = appointments.filter(apt => {
    if (selectedDate && apt.date !== selectedDate) return false
    if (searchTerm) {
      const search = searchTerm.toLowerCase()
      return (
        apt.userName.toLowerCase().includes(search) ||
        apt.userEmail.toLowerCase().includes(search) ||
        apt.date.includes(search) ||
        apt.timeSlot.includes(search)
      )
    }
    return true
  })

  // Grouper par date
  const appointmentsByDate = filteredAppointments.reduce((acc, apt) => {
    if (!acc[apt.date]) acc[apt.date] = []
    acc[apt.date].push(apt)
    return acc
  }, {} as Record<string, Appointment[]>)

  // Ajouter une date seule
  const handleAddDate = () => {
    if (!manualDate) {
      alert('Veuillez sélectionner une date')
      return
    }

    // Vérifier que c'est un mardi ou jeudi
    if (!isAvailableDay(manualDate)) {
      alert('Les rendez-vous sont disponibles uniquement le mardi et le jeudi')
      return
    }

    const result = addAvailableDate(manualDate)
    if (result.success) {
      setManualDate('')
      reloadAllData()
      alert(result.message)
    } else {
      alert(result.message)
    }
  }

  // Ajouter manuellement une date avec créneau
  const handleAddManualSlot = () => {
    if (!manualDate || !manualTimeSlot) {
      alert('Veuillez remplir la date et le créneau')
      return
    }

    // Vérifier que c'est un mardi ou jeudi
    if (!isAvailableDay(manualDate)) {
      alert('Les rendez-vous sont disponibles uniquement le mardi et le jeudi')
      return
    }

    // Ajouter la date si elle n'existe pas
    const dates = loadAvailableDates()
    if (!dates.includes(manualDate)) {
      const result = addAvailableDate(manualDate)
      if (!result.success) {
        alert(result.message)
        return
      }
    }

    // Ajouter le créneau s'il n'existe pas
    const slots = loadAvailableTimeSlots()
    const normalizedSlot = manualTimeSlot.trim()
    if (!slots.includes(normalizedSlot)) {
      const result = addAvailableTimeSlot(normalizedSlot)
      if (!result.success) {
        alert(result.message)
        return
      }
    }

    setManualDate('')
    setManualTimeSlot('')
    reloadAllData()
    alert('Créneau ajouté avec succès')
  }

  // Supprimer une date
  const handleRemoveDate = (date: string) => {
    const [year, month, day] = date.split('-').map(Number)
    const dateObj = new Date(year, month - 1, day)
    const dayName = getDayName(date)
    const dateFormatted = dateObj.toLocaleDateString('fr-FR', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    })

    // Vérifier si la date est utilisée dans des rendez-vous
    const appointmentsOnDate = appointments.filter(apt => apt.date === date)
    if (appointmentsOnDate.length > 0) {
      if (!confirm(`Attention: ${appointmentsOnDate.length} rendez-vous existe(nt) pour cette date. Voulez-vous quand même la supprimer ?`)) {
        return
      }
    }

    if (confirm(`Supprimer la date ${dayName} ${dateFormatted} ?`)) {
      const result = removeAvailableDate(date)
      
      if (result) {
        reloadAllData()
        alert('Date supprimée avec succès')
      } else {
        alert('Erreur lors de la suppression. La date n\'a peut-être pas été trouvée.')
      }
    }
  }

  // Supprimer un créneau
  const handleRemoveTimeSlot = (slot: string) => {
    // Vérifier si le créneau est utilisé dans des rendez-vous
    const appointmentsUsingSlot = appointments.filter(apt => apt.timeSlot === slot)
    if (appointmentsUsingSlot.length > 0) {
      if (!confirm(`Attention: ${appointmentsUsingSlot.length} rendez-vous utilise(nt) ce créneau. Voulez-vous quand même le supprimer ?`)) {
        return
      }
    }

    if (confirm(`Supprimer le créneau ${slot} ?`)) {
      const result = removeAvailableTimeSlot(slot)
      
      if (result) {
        reloadAllData()
        alert('Créneau supprimé avec succès')
      } else {
        alert('Erreur lors de la suppression. Le créneau n\'a peut-être pas été trouvé dans la liste des créneaux personnalisés.')
      }
    }
  }

  // Générer automatiquement les créneaux fixes
  const handleAutoGenerate = () => {
    // Générer les dates (mardis et jeudis)
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    
    const dates: string[] = []
    let currentDate = new Date(today)
    let found = 0
    let maxIterations = 200 // Augmenter pour avoir plus de dates
    
    while (found < autoGenerateCount && maxIterations > 0) {
      const year = currentDate.getFullYear()
      const month = currentDate.getMonth() + 1
      const day = currentDate.getDate()
      const dateString = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
      
      if (isAvailableDay(dateString)) {
        // Vérifier si la date n'existe pas déjà
        const existingDates = loadAvailableDates()
        if (!existingDates.includes(dateString)) {
          // Ajouter la date
          const result = addAvailableDate(dateString)
          if (result.success) {
            dates.push(dateString)
            found++
          }
        }
      }
      
      currentDate.setDate(currentDate.getDate() + 1)
      maxIterations--
    }
    
    // Recharger toutes les données
    reloadAllData()
    
    if (dates.length > 0) {
      alert(`${dates.length} date(s) ajoutée(s) avec succès (Mardis et Jeudis)`)
    } else {
      alert('Aucune nouvelle date n\'a pu être ajoutée. Les dates existent peut-être déjà.')
    }
  }

  // Obtenir les créneaux actifs
  const activeTimeSlots = getAvailableTimeSlotsList()

  // Obtenir les statistiques pour une date
  const getDateStats = (date: string) => {
    const dateAppointments = getAppointmentsByDate(date)
    return activeTimeSlots.map(slot => {
      const bookings = dateAppointments.filter(apt => apt.timeSlot === slot)
      return {
        slot,
        booked: bookings.length,
        available: MAX_BOOKINGS_PER_SLOT - bookings.length
      }
    })
  }

  // Supprimer un rendez-vous
  const handleCancelAppointment = (id: string) => {
    if (confirm('Annuler ce rendez-vous ?')) {
      if (cancelAppointment(id)) {
        const updated = loadAppointments()
        updated.sort((a, b) => {
          if (a.date !== b.date) return a.date.localeCompare(b.date)
          return a.timeSlot.localeCompare(b.timeSlot)
        })
        setAppointments(updated)
        alert('Rendez-vous annulé')
      }
    }
  }

  return (
    <div className="min-h-screen bg-noir-950 py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-yellow-500/10 border border-yellow-500/30 rounded-full mb-4">
            <Calendar className="w-4 h-4 text-yellow-500" />
            <span className="text-sm font-medium text-yellow-500">GESTION DES RENDEZ-VOUS</span>
          </div>
          <h1 className="text-4xl font-bold mb-2">Agenda Wavignies</h1>
          <p className="text-gray-400">Gérez les dates, créneaux et rendez-vous</p>
        </div>

        {/* Statistiques */}
        <div className="grid md:grid-cols-4 gap-4 mb-8">
          <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-4">
            <div className="text-2xl font-bold text-yellow-500 mb-1">{appointments.length}</div>
            <div className="text-sm text-gray-400">Rendez-vous</div>
          </div>
          <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-4">
            <div className="text-2xl font-bold text-green-500 mb-1">{Object.keys(appointmentsByDate).length}</div>
            <div className="text-sm text-gray-400">Jours avec RDV</div>
          </div>
          <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-4">
            <div className="text-2xl font-bold text-blue-500 mb-1">{customDates.length}</div>
            <div className="text-sm text-gray-400">Dates personnalisées</div>
          </div>
          <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-4">
            <div className="text-2xl font-bold text-purple-500 mb-1">{activeTimeSlots.length}</div>
            <div className="text-sm text-gray-400">Créneaux actifs</div>
          </div>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 mb-8">
          {/* Colonne gauche - Ajout manuel */}
          <div className="space-y-6">
            {/* Ajout manuel */}
            <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-6">
              <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                <Plus className="w-5 h-5 text-blue-500" />
                Ajouter manuellement
              </h2>
              
              <div className="space-y-6">
                {/* Ajouter une date seule */}
                <div>
                  <h3 className="text-sm font-semibold mb-3 text-gray-300">Ajouter une date</h3>
                  <div className="space-y-3">
                    <div>
                      <label className="block text-sm font-medium mb-2 text-gray-300">
                        Date (Mardi ou Jeudi)
                      </label>
                      <input
                        type="date"
                        value={manualDate}
                        onChange={(e) => setManualDate(e.target.value)}
                        min={new Date().toISOString().split('T')[0]}
                        className="w-full px-4 py-2 bg-noir-900 border border-noir-700 rounded-lg text-white text-sm focus:border-blue-500 focus:outline-none"
                      />
                      {manualDate && !isAvailableDay(manualDate) && (
                        <p className="text-xs text-red-400 mt-1">⚠️ Doit être un mardi ou jeudi</p>
                      )}
                    </div>
                    <button
                      onClick={handleAddDate}
                      disabled={!manualDate || !isAvailableDay(manualDate)}
                      className="w-full px-4 py-2 bg-green-500 text-white font-semibold rounded-lg hover:bg-green-400 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
                    >
                      <Plus className="w-4 h-4" />
                      Ajouter la date
                    </button>
                  </div>
                </div>

                {/* Séparateur */}
                <div className="border-t border-noir-700 pt-4">
                  <h3 className="text-sm font-semibold mb-3 text-gray-300">Ajouter une date + créneau</h3>
                  <div className="space-y-3">
                    <div>
                      <label className="block text-sm font-medium mb-2 text-gray-300">
                        Date (Mardi ou Jeudi)
                      </label>
                      <input
                        type="date"
                        value={manualDate}
                        onChange={(e) => setManualDate(e.target.value)}
                        min={new Date().toISOString().split('T')[0]}
                        className="w-full px-4 py-2 bg-noir-900 border border-noir-700 rounded-lg text-white text-sm focus:border-blue-500 focus:outline-none"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium mb-2 text-gray-300">
                        Créneau horaire
                      </label>
                      <input
                        type="text"
                        value={manualTimeSlot}
                        onChange={(e) => setManualTimeSlot(e.target.value)}
                        placeholder="Ex: 15h-16h"
                        className="w-full px-4 py-2 bg-noir-900 border border-noir-700 rounded-lg text-white text-sm focus:border-blue-500 focus:outline-none"
                      />
                      <p className="text-xs text-gray-500 mt-1">Format: 15h-16h</p>
                    </div>

                    <button
                      onClick={handleAddManualSlot}
                      disabled={!manualDate || !manualTimeSlot || !isAvailableDay(manualDate)}
                      className="w-full px-4 py-2 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-400 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
                    >
                      <Plus className="w-4 h-4" />
                      Ajouter date + créneau
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Génération automatique */}
            <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-6">
              <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                <RefreshCw className="w-5 h-5 text-green-500" />
                Génération automatique
              </h2>
              <p className="text-sm text-gray-400 mb-4">
                Générez automatiquement les créneaux fixes (Mardis et Jeudis)
              </p>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-2 text-gray-300">
                    Nombre de dates à générer
                  </label>
                  <input
                    type="number"
                    min="1"
                    max="100"
                    value={autoGenerateCount}
                    onChange={(e) => setAutoGenerateCount(parseInt(e.target.value) || 20)}
                    className="w-full px-4 py-2 bg-noir-900 border border-noir-700 rounded-lg text-white text-sm focus:border-green-500 focus:outline-none"
                  />
                </div>

                <button
                  onClick={handleAutoGenerate}
                  className="w-full px-4 py-2 bg-green-500 text-white font-semibold rounded-lg hover:bg-green-400 transition-colors flex items-center justify-center gap-2"
                >
                  <RefreshCw className="w-4 h-4" />
                  Générer {autoGenerateCount} dates
                </button>

                {autoGeneratedDates.length > 0 && (
                  <div className="mt-4">
                    <p className="text-sm text-gray-400 mb-2">
                      {autoGeneratedDates.length} dates générées
                    </p>
                    <div className="max-h-40 overflow-y-auto grid grid-cols-2 gap-2">
                      {autoGeneratedDates.slice(0, 10).map(date => (
                        <div
                          key={date}
                          className="p-2 bg-noir-900 rounded text-xs text-gray-300"
                        >
                          {getDayName(date)} {new Date(date).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' })}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Colonne droite - Liste des créneaux */}
          <div className="space-y-6">
            {/* Dates personnalisées */}
            <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold flex items-center gap-2">
                  <Calendar className="w-5 h-5 text-yellow-500" />
                  Dates disponibles ({customDates.length})
                </h2>
                <button
                  onClick={reloadAllData}
                  className="p-2 text-gray-400 hover:text-white hover:bg-noir-700 rounded transition-colors"
                  title="Rafraîchir"
                >
                  <RefreshCw className="w-4 h-4" />
                </button>
              </div>
              {customDates.length === 0 ? (
                <p className="text-sm text-gray-400">Aucune date personnalisée</p>
              ) : (
                <div className="space-y-2 max-h-60 overflow-y-auto">
                  {customDates.map(date => {
                    const appointmentsCount = appointments.filter(apt => apt.date === date).length
                    const [year, month, day] = date.split('-').map(Number)
                    const dateObj = new Date(year, month - 1, day)
                    
                    return (
                      <div
                        key={date}
                        className="flex items-center justify-between p-3 bg-noir-900 rounded-lg border border-noir-700 hover:border-red-500/50 transition-colors group"
                      >
                        <div className="flex-1">
                          <div className="font-semibold text-white flex items-center gap-2">
                            <Calendar className="w-4 h-4 text-yellow-500" />
                            {getDayName(date)} {dateObj.toLocaleDateString('fr-FR', {
                              day: 'numeric',
                              month: 'long',
                              year: 'numeric'
                            })}
                            {appointmentsCount > 0 && (
                              <span className="text-xs text-yellow-400 bg-yellow-500/20 px-2 py-0.5 rounded">
                                {appointmentsCount} RDV
                              </span>
                            )}
                          </div>
                        </div>
                        <button
                          onClick={() => handleRemoveDate(date)}
                          className="p-2 text-red-400 hover:text-red-300 hover:bg-red-500/20 rounded transition-colors flex items-center justify-center"
                          title="Supprimer cette date"
                        >
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>

            {/* Créneaux horaires */}
            <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-6">
              <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                <Clock className="w-5 h-5 text-purple-500" />
                Créneaux horaires ({activeTimeSlots.length})
              </h2>
              {activeTimeSlots.length === 0 ? (
                <p className="text-sm text-gray-400">Aucun créneau défini</p>
              ) : (
                <div className="space-y-2 max-h-60 overflow-y-auto">
                  {activeTimeSlots.map(slot => {
                    const isCustom = customTimeSlots.includes(slot)
                    const appointmentsCount = appointments.filter(apt => apt.timeSlot === slot).length
                    return (
                      <div
                        key={slot}
                        className={`p-3 rounded-lg border relative group ${
                          isCustom
                            ? 'border-purple-500/50 bg-purple-500/10'
                            : 'border-gray-500/50 bg-gray-500/10'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2 flex-1">
                            <Clock className={`w-4 h-4 ${isCustom ? 'text-purple-400' : 'text-gray-400'}`} />
                            <span className={`font-semibold ${isCustom ? 'text-purple-300' : 'text-gray-300'}`}>
                              {slot}
                            </span>
                            {appointmentsCount > 0 && (
                              <span className="text-xs text-yellow-400 bg-yellow-500/20 px-2 py-0.5 rounded">
                                {appointmentsCount} RDV
                              </span>
                            )}
                          </div>
                          <button
                            onClick={() => handleRemoveTimeSlot(slot)}
                            className={`p-2 text-red-400 hover:text-red-300 hover:bg-red-500/20 rounded transition-colors flex items-center justify-center ${
                              !isCustom ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'
                            }`}
                            title={isCustom ? "Supprimer ce créneau" : "Ce créneau est par défaut. Ajoutez-le manuellement pour pouvoir le supprimer."}
                            disabled={!isCustom}
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                        {!isCustom && (
                          <p className="text-xs text-gray-500 mt-1">Par défaut (non supprimable)</p>
                        )}
                        {isCustom && (
                          <p className="text-xs text-purple-400 mt-1">Personnalisé</p>
                        )}
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Filtres et recherche */}
        <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-6 mb-8">
          <div className="grid md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium mb-2 text-gray-300">Rechercher</label>
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Nom, email, date..."
                  className="w-full pl-10 pr-4 py-2 bg-noir-900 border border-noir-700 rounded-lg text-white text-sm focus:border-yellow-500 focus:outline-none"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium mb-2 text-gray-300">Filtrer par date</label>
              <input
                type="date"
                value={selectedDate}
                onChange={(e) => setSelectedDate(e.target.value)}
                className="w-full px-4 py-2 bg-noir-900 border border-noir-700 rounded-lg text-white text-sm focus:border-yellow-500 focus:outline-none"
              />
            </div>
          </div>
        </div>

        {/* Liste des rendez-vous */}
        {filteredAppointments.length === 0 ? (
          <div className="bg-noir-800/50 border border-noir-700 rounded-xl p-12 text-center">
            <Calendar className="w-16 h-16 text-gray-500 mx-auto mb-4" />
            <p className="text-gray-400">Aucun rendez-vous trouvé</p>
          </div>
        ) : (
          <div className="space-y-6">
            {Object.entries(appointmentsByDate).map(([date, dateAppointments]) => {
              const stats = getDateStats(date)
              const dayName = getDayName(date)
              
              return (
                <div key={date} className="bg-noir-800/50 border border-noir-700 rounded-xl p-6">
                  <div className="flex items-center justify-between mb-4 pb-4 border-b border-noir-700">
                    <h3 className="text-xl font-bold flex items-center gap-2">
                      <Calendar className="w-5 h-5 text-yellow-500" />
                      {dayName} {new Date(date).toLocaleDateString('fr-FR', {
                        day: 'numeric',
                        month: 'long',
                        year: 'numeric'
                      })}
                    </h3>
                    <span className="text-sm text-gray-400">{dateAppointments.length} rendez-vous</span>
                  </div>

                  <div className="grid grid-cols-3 gap-4 mb-4">
                    {stats.map(stat => (
                      <div
                        key={stat.slot}
                        className={`p-3 rounded-lg border ${
                          stat.available > 0
                            ? 'border-green-500/50 bg-green-500/10'
                            : 'border-red-500/50 bg-red-500/10'
                        }`}
                      >
                        <div className="text-sm font-semibold mb-1">{stat.slot}</div>
                        <div className="text-xs text-gray-400">
                          {stat.booked}/{MAX_BOOKINGS_PER_SLOT} réservé(s)
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="space-y-3">
                    {dateAppointments.map(apt => (
                      <div
                        key={apt.id}
                        className="bg-noir-900/50 border border-noir-700 rounded-lg p-4 flex items-center justify-between"
                      >
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-2">
                            <Clock className="w-4 h-4 text-yellow-500" />
                            <span className="font-semibold">{apt.timeSlot}</span>
                          </div>
                          <div className="space-y-1 text-sm">
                            <div className="flex items-center gap-2 text-gray-300">
                              <User className="w-4 h-4 text-gray-500" />
                              <span>{apt.userName}</span>
                            </div>
                            <div className="flex items-center gap-2 text-gray-400">
                              <Mail className="w-4 h-4 text-gray-500" />
                              <span>{apt.userEmail}</span>
                            </div>
                            {apt.userPhone && (
                              <div className="flex items-center gap-2 text-gray-400">
                                <Phone className="w-4 h-4 text-gray-500" />
                                <span>{apt.userPhone}</span>
                              </div>
                            )}
                          </div>
                        </div>
                        <button
                          onClick={() => handleCancelAppointment(apt.id)}
                          className="p-2 text-red-400 hover:text-red-300 hover:bg-red-500/10 rounded-lg transition-colors"
                          title="Annuler"
                        >
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}
